export const productTypes = [
  {
    productId: 1, //type of product id
    products: [
      {
        id: 1,
        merchantId: 1,
        name: 'cafe1',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 2,
        merchantId: 2,
        name: 'cafe2',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 3,
        merchantId: 2,
        name: 'cafe3',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
    ],
  },
  {
    productId: 2, //type of product id
    products: [
      {
        id: 4,
        merchantId: 1,
        name: 'cacao1',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 5,
        productId: 1,
        merchantId: 2,
        name: 'cacao2',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 6,
        productId: 1,
        merchantId: 2,
        name: 'cacao3',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
    ],
  },
  {
    productId: 3, //type of product id
    products: [
      {
        id: 7,
        merchantId: 1,
        name: 'miel1',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 8,
        productId: 1,
        merchantId: 2,
        name: 'miel2',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 9,
        productId: 1,
        merchantId: 2,
        name: 'miel3',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 10,
        productId: 1,
        merchantId: 2,
        name: 'miel4',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
    ],
  },
  {
    productId: 4, //type of product id
    products: [
      {
        id: 11,
        merchantId: 1,
        name: 'artesania1',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 12,
        productId: 1,
        merchantId: 2,
        name: 'artesania2',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 13,
        productId: 1,
        merchantId: 2,
        name: 'artesania3',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
    ],
  },
  {
    productId: 5, //type of product id
    products: [
      {
        id: 14,
        merchantId: 1,
        name: 'piel1',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 15,
        productId: 1,
        merchantId: 2,
        name: 'piel2',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 16,
        productId: 1,
        merchantId: 2,
        name: 'piel3',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
    ],
  },
  {
    productId: 6, //type of product id
    products: [
      {
        id: 17,
        merchantId: 1,
        name: 'herb1',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 18,
        productId: 1,
        merchantId: 2,
        name: 'herb2',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
      {
        id: 19,
        productId: 1,
        merchantId: 2,
        name: 'herb3',
        price: '250',
        img: 'https://via.placeholder.com/250',
        productType: 'Cafes de origen',
        description: 'lorem',
      },
    ],
  },
]
